// Pixel-art icon set for PiXeL QuiLT 2000
// Each icon is a 16x16 grid. k=black g=gray l=light gray w=white n=navy b=blue s=light blue .=transparent

const ICONS = {
  pencil: [
    '................',
    '............k...',
    '...........kwk..',
    '..........kwwwk.',
    '.........kgwwk..',
    '........kbggk...',
    '.......kbbbk....',
    '......kbbbk.....',
    '.....kbbbk......',
    '....kbbbk.......',
    '...kbbbk........',
    '..kllbk.........',
    '..kllk..........',
    '.kkkk...........',
    '.kk.............',
    '................',
  ],
  eraser: [
    '................',
    '................',
    '................',
    '................',
    '.....kkkkkkkkk..',
    '....ksskwwwwkk..',
    '...ksskwwwwkgk..',
    '..kkkkkkkkkggk..',
    '..kbbkllllkggk..',
    '..kbbkllllkggk..',
    '..kbbkllllkgk...',
    '..kbbkllllkk....',
    '..kkkkkkkkk.....',
    '................',
    '................',
    '................',
  ],
  line: [
    '................',
    '................',
    '.............k..',
    '............kk..',
    '...........kk...',
    '..........kk....',
    '.........kk.....',
    '........kk......',
    '.......kk.......',
    '......kk........',
    '.....kk.........',
    '....kk..........',
    '...kk...........',
    '..kk............',
    '................',
    '................',
  ],
  rect: [
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..kkkkkkkkkkkk..',
    '..kk........kk..',
    '..kk........kk..',
    '..kk........kk..',
    '..kk........kk..',
    '..kkkkkkkkkkkk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
    '................',
  ],
  ellipse: [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kkkkkkkk....',
    '...kkk....kkk...',
    '..kkk......kkk..',
    '..kk........kk..',
    '..kk........kk..',
    '..kk........kk..',
    '..kk........kk..',
    '..kkk......kkk..',
    '...kkk....kkk...',
    '....kkkkkkkk....',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  fill: [
    '................',
    '.....kkkkkk.....',
    '....k......k....',
    '....k......k....',
    '..kkkkkkkkkkkk..',
    '.bkbbbbbbbbbbk..',
    '.b.kwblllbggk...',
    '.b.kwblllbggk...',
    '.b.kwbllllggk...',
    '...kwwllllggk...',
    '.b..kwwllggk....',
    '.b..kwwllggk....',
    '....kwwllggk....',
    '....kwwllggk....',
    '....kkkkkkkk....',
    '................',
  ],
  picker: [
    '................',
    '................',
    '...........kk...',
    '..........kkkk..',
    '.........kkkkk..',
    '.......kgkkkk...',
    '.......kggkk....',
    '......kwwgg.....',
    '.....kwwwkk.....',
    '....kbwwk.......',
    '...kbbbk........',
    '..kbbbk.........',
    '..bbbk..........',
    '.k.bk...........',
    '.kk.............',
    '................',
  ],
  undo: [
    '................',
    '....k...........',
    '...kk...........',
    '..kkk...........',
    '.kkkkkkkkkkk....',
    '.kkkkkkkkkkkk...',
    '..kkk.......kk..',
    '...kk.......kk..',
    '....k.......kk..',
    '............kk..',
    '...........kk...',
    '.......kkkkk....',
    '.......kkkk.....',
    '................',
    '................',
    '................',
  ],
  picture: [
    '................',
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kssssssssssssk.',
    '.ksssssssswwssk.',
    '.kssssnssswwssk.',
    '.ksssnnnssssssk.',
    '.kssnnnnnnnsssk.',
    '.kssnnnnnnnnssk.',
    '.ksnnnnnnnnnnsk.',
    '.knnnnnnnnnnnnk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  trash: [
    '................',
    '................',
    '......kkkk......',
    '......k..k......',
    '...kkkkkkkkkk...',
    '...kkkkkkkkkk...',
    '....kllllllk....',
    '....kllllllk....',
    '....klglgglk....',
    '....klglgglk....',
    '....klglggk.....',
    '.....kglggk.....',
    '.....kglggk.....',
    '.....kllllk.....',
    '.....kkkkkk.....',
    '................',
  ],
  folder: [
    '................',
    '................',
    '................',
    '.kkkkkk.........',
    '.kllllk.........',
    '.kkkkkkkkkkkkkk.',
    '.kwwwwwwwwwwwwk.',
    '.kwlllllllllllk.',
    '.kwlllllllllllk.',
    '.kwlllllllllllk.',
    '.kwlllllllllllk.',
    '.kwlllllllllllk.',
    '.kwlllllllllllk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  settings: [
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kllllllllllllk.',
    '.kllllllkkklllk.',
    '.klgggggknkgglk.',
    '.kllllllkkklllk.',
    '.kllllllllllllk.',
    '.kllkkklllllllk.',
    '.klgknkgggggglk.',
    '.kllkkklllllllk.',
    '.kllllllllllllk.',
    '.klllllllkkkllk.',
    '.klggggggknkglk.',
    '.klllllllkkkllk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  quilt: [
    '................',
    '.kkkkkkkkkkkkkk.',
    '.knnnnnkksssssk.',
    '.knwnnnkksssssk.',
    '.knnwnnkksssssk.',
    '.knnnwnkksssssk.',
    '.knnnnnkksssssk.',
    '.kkkkkkkkkkkkkk.',
    '.kkkkkkkkkkkkkk.',
    '.kssssskkbbbbbk.',
    '.kssssskkbwbbbk.',
    '.kssssskkbbwbbk.',
    '.kssssskkbbbwbk.',
    '.kssssskkbbbbbk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  chart: [
    '................',
    '.kkkkgkkkkgkkkk.',
    '.knnngwwwwgwwwk.',
    '.knnngwwwwgwwwk.',
    '.knnngwwwwgwwwk.',
    '.gggggggggggggg.',
    '.kwwwgwwwwgnnnk.',
    '.kwwwgwwwwgnnnk.',
    '.kwwwgwwwwgnnnk.',
    '.kwwwgwwwwgwwwk.',
    '.gggggggggggggg.',
    '.kwwwgnnnwgwwwk.',
    '.kwwwgnnnwgwwwk.',
    '.kwwwgnnnwgwwwk.',
    '.kkkkgkkkkgkkkk.',
    '................',
  ],
  touch: [
    '................',
    '.gggggggggggggg.',
    '.gwwwwwwwwwwwwg.',
    '.gwkkkkkkkkkkwg.',
    '.gwkssskkssskwg.',
    '.gwkssskkssskwg.',
    '.gwkssskkssskwg.',
    '.gwkkkkkkkkkkwg.',
    '.gwkkkkkkkkkkwg.',
    '.gwkssskknnnkwg.',
    '.gwkssskknnnkwg.',
    '.gwkssskknnnkwg.',
    '.gwkkkkkkkkkkwg.',
    '.gwwwwwwwwwwwwg.',
    '.gggggggggggggg.',
    '................',
  ],
  save: [
    '................',
    '.kkkkkkkkkkkkkk.',
    '.knnkllllnnknnk.',
    '.knnkllllnnknnk.',
    '.knnkllllnnknnk.',
    '.knnkkkkkkkknnk.',
    '.knnnnnnnnnnnnk.',
    '.knnnnnnnnnnnnk.',
    '.knkkkkkkkkkknk.',
    '.knkwwwwwwwwknk.',
    '.knkwggggggwknk.',
    '.knkwwwwwwwwknk.',
    '.knkwggggggwknk.',
    '.knkwwwwwwwwknk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  print: [
    '................',
    '....kkkkkkkk....',
    '....kwwwwwwk....',
    '....kwwwwwwk....',
    '....kwwwwwwk....',
    '.kkkkkkkkkkkkkk.',
    '.kllllllllllllk.',
    '.kllllllllllblk.',
    '.kllllllllllllk.',
    '.klgggggggggglk.',
    '.kllkkkkkkkkllk.',
    '.kkkkwwwwwwkkkk.',
    '....kwggggwk....',
    '....kwwwwwwk....',
    '....kkkkkkkk....',
    '................',
  ],
  copy: [
    '................',
    '.....kkkkkk.....',
    '..kkkkllllkkkk..',
    '..kggkkkkkkggk..',
    '..kgkkkkkkkkgk..',
    '..kgkwwwwwwkgk..',
    '..kgknnnnnnkgk..',
    '..kgkwwwwwwkgk..',
    '..kgknnnnnnkgk..',
    '..kgkwwwwwwkgk..',
    '..kgknnnnnnkgk..',
    '..kgkwwwwwwkgk..',
    '..kgkwwwwwwkgk..',
    '..kgkkkkkkkkgk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
};
const ICON_COLORS = { k: '#000000', g: '#808080', l: '#c0c0c0', w: '#ffffff', n: '#000080', b: '#1084d0', s: '#a6caf0' };

// Turns a grid into a crisp SVG, merging horizontal runs of the same color into one <rect>.
function iconSVG(name) {
  const rows = ICONS[name];
  if (!rows) return '';
  let r = '';
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length;) {
      const c = row[x];
      let w = 1;
      while (row[x + w] === c) w++;
      if (c !== '.') r += `<rect x="${x}" y="${y}" width="${w}" height="1" fill="${ICON_COLORS[c]}"/>`;
      x += w;
    }
  });
  return `<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" shape-rendering="crispEdges">${r}</svg>`;
}

// Fills every <span class="ic" data-icon="name"></span> on the page.
document.querySelectorAll('.ic[data-icon]').forEach(el => (el.innerHTML = iconSVG(el.dataset.icon)));
